version: '3'

services:
  egadeduc-postgres:
    image: postgres
    environment:
      POSTGRES_DB: "egadeduc"
      POSTGRES_USER: "egadeduc"
      POSTGRES_PASSWORD: "egadeduc"
    ports:
      - "15432:5432"
    volumes:
      - ./docker-content/PostgreSQL:/var/lib/postgresql/data
    networks:
      - egadeduc-network
  egadeduc-redis:
    image: redis
    command: redis-server --requirepass k.zn9DAV+T
    ports:
      - "16379:6379"
    networks:
      - egadeduc-network
  egadeduc-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=egadeduc
      - MONGODB_ADMIN_PASS=egadeduc
      - MONGODB_APPLICATION_DATABASE=egadeduc
      - MONGODB_APPLICATION_USER=egadeduc
      - MONGODB_APPLICATION_PASS=egadeduc
    ports:
      - "17017:27017"
    volumes:
      - ./docker-content/MongoDB:/var/lib/mongoDB/data
    networks:
      - egadeduc-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: egadeduc-go-login-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-content/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=egadeduc
      - RABBITMQ_DEFAULT_PASS=egadeduc

networks:
  egadeduc-network:
    driver: bridge
